# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

formats: all

python:
   install:
      - requirements: docs/envs/requirements-doc.txt
