# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Discorpy_ga

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os-python-version:
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.10"
          - os: macos-latest
            python-version: "3.8.16"
          - os: macos-latest
            python-version: "3.9.13"
          - os: macos-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.8"
          - os: windows-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.os-python-version.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.os-python-version.python-version }}
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8    
        python setup.py install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        python -m unittest discover -s tests -v
